# Generated by Django 5.1.4 on 2025-01-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_year', models.CharField(max_length=4)),
                ('to_year', models.CharField(max_length=4)),
                ('batch_type', models.CharField(max_length=255)),
            ],
        ),
    ]
