# Generated by Django 5.1.4 on 2025-01-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('school_year', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('batch_type', models.CharField(choices=[('Regular', 'Regular'), ('Mid-Year', 'Mid-Year')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='graduates/photos/')),
            ],
        ),
    ]
