# Generated by Django 5.1.4 on 2025-01-18 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_graduate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduate',
            name='batch_type',
        ),
        migrations.AddField(
            model_name='graduate',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graduates', to='main.batch'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='batch',
            name='from_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='to_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='graduate_photos/'),
        ),
    ]
