# Generated by Django 5.1.4 on 2025-01-19 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_graduate_batch_type_graduate_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduate',
            name='school_year',
        ),
        migrations.AlterField(
            model_name='graduate',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.batch'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='graduates/photos/'),
        ),
    ]
