# Generated by Django 5.1.4 on 2025-01-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_graduate_school_year_alter_graduate_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='ambition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
