# Generated by Django 5.1.4 on 2025-01-22 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_graduate_ambition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='ambition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField()),
                ('private_key', models.TextField()),
                ('graduate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.graduate')),
            ],
        ),
    ]
