# Generated by Django 5.2 on 2025-04-07 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_graduate_ambition_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yearbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil_status', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('region', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=20)),
                ('honors', models.CharField(blank=True, max_length=255, null=True)),
                ('grad_reasons', models.TextField(blank=True, null=True)),
                ('other_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_status', models.CharField(max_length=30)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('income', models.CharField(blank=True, max_length=100, null=True)),
                ('agreed_to_privacy', models.BooleanField(default=False)),
                ('graduate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.graduate')),
            ],
        ),
    ]
