# Generated by Django 5.2 on 2025-05-10 00:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_yearbook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearbook',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
