# Generated by Django 5.2 on 2025-05-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_yearbook_submitted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduateTracerForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('civil_status', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('region', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=100)),
                ('residence_location', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('college_name', models.CharField(max_length=255)),
                ('year_graduated', models.CharField(max_length=10)),
                ('honors', models.CharField(blank=True, max_length=255)),
                ('exam_passed', models.CharField(blank=True, max_length=255)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_rating', models.CharField(blank=True, max_length=50)),
                ('undergrad_reasons', models.TextField(blank=True)),
                ('grad_reasons', models.TextField(blank=True)),
                ('grad_reasons_other', models.CharField(blank=True, max_length=255)),
                ('trainings', models.TextField(blank=True)),
                ('advance_reason', models.CharField(blank=True, max_length=100)),
                ('employment_status', models.CharField(max_length=50)),
                ('unemployed_reasons', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('business_line', models.CharField(blank=True, max_length=100)),
                ('work_location', models.CharField(blank=True, max_length=100)),
                ('first_job', models.CharField(blank=True, max_length=10)),
                ('stay_reasons', models.TextField(blank=True)),
                ('job_course_relation', models.CharField(blank=True, max_length=10)),
                ('job_finding_time', models.CharField(blank=True, max_length=20)),
                ('job_accept_reasons', models.TextField(blank=True)),
                ('job_change_reasons', models.TextField(blank=True)),
                ('first_job_duration', models.CharField(blank=True, max_length=50)),
                ('first_job_position', models.CharField(blank=True, max_length=50)),
                ('current_job_position', models.CharField(blank=True, max_length=50)),
                ('current_employer_name', models.CharField(blank=True, max_length=255)),
                ('current_employer_address', models.CharField(blank=True, max_length=255)),
                ('current_supervisor_name', models.CharField(blank=True, max_length=255)),
                ('current_employer_contact', models.CharField(blank=True, max_length=20)),
                ('initial_salary', models.CharField(blank=True, max_length=50)),
                ('curriculum_relevance', models.CharField(blank=True, max_length=20)),
                ('college_competencies', models.TextField(blank=True)),
                ('other_skills_specified', models.CharField(blank=True, max_length=255)),
                ('data_privacy', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
